CREATE TABLE `homestead`.`sample01` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `policyID` VARCHAR(255) NULL,
  `statecode` VARCHAR(255) NULL,
  `county` VARCHAR(255) NULL,
  `eq_site_limit` VARCHAR(255) NULL,
  `hu_site_limit` VARCHAR(255) NULL,
  `fl_site_limit` VARCHAR(255) NULL,
  `fr_site_limit` VARCHAR(255) NULL,
  `tiv_2011` VARCHAR(255) NULL,
  `tiv_2012` VARCHAR(255) NULL,
  `eq_site_deductible` VARCHAR(255) NULL,
  `hu_site_deductible` VARCHAR(255) NULL,
  `fl_site_deductible` VARCHAR(255) NULL,
  `fr_site_deductible` VARCHAR(255) NULL,
  `point_latitude` VARCHAR(255) NULL,
  `point_longitude` VARCHAR(255) NULL,
  `line` VARCHAR(255) NULL, 
  `construction` VARCHAR(255) NULL, 
  `point_granularity` VARCHAR(255) NULL,  
  PRIMARY KEY (`id`));
